<?php
$coworking_slider_sc = coworking_get_theme_option( 'front_page_title_shortcode' );
if ( ! empty( $coworking_slider_sc ) && strpos( $coworking_slider_sc, '[' ) !== false && strpos( $coworking_slider_sc, ']' ) !== false ) {

	?><div class="front_page_section front_page_section_title front_page_section_slider front_page_section_title_slider
		<?php
		if ( coworking_get_theme_option( 'front_page_title_stack' ) ) {
			echo ' sc_stack_section_on';
		}
		?>
	">
	<?php
		// Add anchor
		$coworking_anchor_icon = coworking_get_theme_option( 'front_page_title_anchor_icon' );
		$coworking_anchor_text = coworking_get_theme_option( 'front_page_title_anchor_text' );
	if ( ( ! empty( $coworking_anchor_icon ) || ! empty( $coworking_anchor_text ) ) && shortcode_exists( 'trx_sc_anchor' ) ) {
		echo do_shortcode(
			'[trx_sc_anchor id="front_page_section_title"'
									. ( ! empty( $coworking_anchor_icon ) ? ' icon="' . esc_attr( $coworking_anchor_icon ) . '"' : '' )
									. ( ! empty( $coworking_anchor_text ) ? ' title="' . esc_attr( $coworking_anchor_text ) . '"' : '' )
									. ']'
		);
	}
		// Show slider (or any other content, generated by shortcode)
		echo do_shortcode( $coworking_slider_sc );
	?>
	</div>
	<?php

} else {

	?>
	<div class="front_page_section front_page_section_title
		<?php
		$coworking_scheme = coworking_get_theme_option( 'front_page_title_scheme' );
		if ( ! empty( $coworking_scheme ) && ! coworking_is_inherit( $coworking_scheme ) ) {
			echo ' scheme_' . esc_attr( $coworking_scheme );
		}
		echo ' front_page_section_paddings_' . esc_attr( coworking_get_theme_option( 'front_page_title_paddings' ) );
		if ( coworking_get_theme_option( 'front_page_title_stack' ) ) {
			echo ' sc_stack_section_on';
		}
		?>
		"
		<?php
		$coworking_css      = '';
		$coworking_bg_image = coworking_get_theme_option( 'front_page_title_bg_image' );
		if ( ! empty( $coworking_bg_image ) ) {
			$coworking_css .= 'background-image: url(' . esc_url( coworking_get_attachment_url( $coworking_bg_image ) ) . ');';
		}
		if ( ! empty( $coworking_css ) ) {
			echo ' style="' . esc_attr( $coworking_css ) . '"';
		}
		?>
	>
	<?php
		// Add anchor
		$coworking_anchor_icon = coworking_get_theme_option( 'front_page_title_anchor_icon' );
		$coworking_anchor_text = coworking_get_theme_option( 'front_page_title_anchor_text' );
	if ( ( ! empty( $coworking_anchor_icon ) || ! empty( $coworking_anchor_text ) ) && shortcode_exists( 'trx_sc_anchor' ) ) {
		echo do_shortcode(
			'[trx_sc_anchor id="front_page_section_title"'
									. ( ! empty( $coworking_anchor_icon ) ? ' icon="' . esc_attr( $coworking_anchor_icon ) . '"' : '' )
									. ( ! empty( $coworking_anchor_text ) ? ' title="' . esc_attr( $coworking_anchor_text ) . '"' : '' )
									. ']'
		);
	}
	?>
		<div class="front_page_section_inner front_page_section_title_inner
		<?php
		if ( coworking_get_theme_option( 'front_page_title_fullheight' ) ) {
			echo ' coworking-full-height sc_layouts_flex sc_layouts_columns_middle';
		}
		?>
			"
			<?php
			$coworking_css      = '';
			$coworking_bg_mask  = coworking_get_theme_option( 'front_page_title_bg_mask' );
			$coworking_bg_color_type = coworking_get_theme_option( 'front_page_title_bg_color_type' );
			if ( 'custom' == $coworking_bg_color_type ) {
				$coworking_bg_color = coworking_get_theme_option( 'front_page_title_bg_color' );
			} elseif ( 'scheme_bg_color' == $coworking_bg_color_type ) {
				$coworking_bg_color = coworking_get_scheme_color( 'bg_color', $coworking_scheme );
			} else {
				$coworking_bg_color = '';
			}
			if ( ! empty( $coworking_bg_color ) && $coworking_bg_mask > 0 ) {
				$coworking_css .= 'background-color: ' . esc_attr(
					1 == $coworking_bg_mask ? $coworking_bg_color : coworking_hex2rgba( $coworking_bg_color, $coworking_bg_mask )
				) . ';';
			}
			if ( ! empty( $coworking_css ) ) {
				echo ' style="' . esc_attr( $coworking_css ) . '"';
			}
			?>
		>
			<div class="front_page_section_content_wrap front_page_section_title_content_wrap content_wrap">
				<?php
				// Caption
				$coworking_caption = coworking_get_theme_option( 'front_page_title_caption' );
				if ( ! empty( $coworking_caption ) || ( current_user_can( 'edit_theme_options' ) && is_customize_preview() ) ) {
					?>
					<h1 class="front_page_section_caption front_page_section_title_caption front_page_block_<?php echo ! empty( $coworking_caption ) ? 'filled' : 'empty'; ?>"><?php echo wp_kses( $coworking_caption, 'coworking_kses_content' ); ?></h1>
					<?php
				}

				// Description (text)
				$coworking_description = coworking_get_theme_option( 'front_page_title_description' );
				if ( ! empty( $coworking_description ) || ( current_user_can( 'edit_theme_options' ) && is_customize_preview() ) ) {
					?>
					<div class="front_page_section_description front_page_section_title_description front_page_block_<?php echo ! empty( $coworking_description ) ? 'filled' : 'empty'; ?>"><?php echo wp_kses( wpautop( $coworking_description ), 'coworking_kses_content' ); ?></div>
					<?php
				}

				// Buttons
				if ( coworking_get_theme_option( 'front_page_title_button1_link' ) != '' || coworking_get_theme_option( 'front_page_title_button2_link' ) != '' ) {
					?>
					<div class="front_page_section_buttons front_page_section_title_buttons">
					<?php
						coworking_show_layout( coworking_customizer_partial_refresh_front_page_title_button1_link() );
						coworking_show_layout( coworking_customizer_partial_refresh_front_page_title_button2_link() );
					?>
					</div>
					<?php
				}
				?>
			</div>
		</div>
	</div>
	<?php
}
